image: "nixos/nix"

stages:
  - test
  - style

variables:
  flags: "--extra-experimental-features nix-command --extra-experimental-features flakes"

flake-check:
  stage: test
  script: nix ${flags} flake check
