image: "nixos/nix"

stages:
  - test
  - pretty

variables:
  flags: '--extra-experimental-features nix-command --extra-experimental-features flakes'

fmt:
  stage: pretty
  script:
    nix ${flags} fmt

lint:
  stage: pretty
  script:
    nix ${flags} run "nixpkgs#statix" -- check .

build-test:
  stage: test
  script:
    nix ${flags} build --no-link .#nixosConfigurations.g14.config.system.build.toplevel
