image: "nixos/nix"

stages:
  - check
  - pretty

variables:
  flags: '--extra-experimental-features nix-command --extra-experimental-features flakes'

flake-check:
  stage: check
  script: nix ${flags} flake check .

fmt:
  stage: pretty
  script:
    nix ${flags} fmt
